apiVersion: v1
kind: Service
metadata:
  name: abhipromethues
  labels:
    app: abhipromethues
spec:
  selector:
    app: abhipromethues
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090

apiVersion: apps/v1
kind: Deployment
metadata:
  name: abhipromethues
  labels:
    app: abhipromethues
spec:
  selector:
    matchLabels:
      app: abhipromethues
  replicas: 1
  template:
    metadata:
      name: mypod
      labels:
        app: abhipromethues
    spec:
      containers:
      - name: abhigrafana-container
        image: vimal13/prometheus
        volumeMounts:
        - name: prometheus-storage-volume
          mountPath: /prometheus/
      volumes:
      - name: prometheus-storage-volume
        persistentVolumeClaim:
          claimName: pvc-prometheus